#!/usr/bin/env node

// Why this file exists.
//
// Gradle's Android build drives the Tauri CLI itself: the generated
// `gen/android/buildSrc/.../BuildTask.kt` runs
//
//     node tauri android android-studio-script --target <arch>
//
// from `src-tauri/` every time it assembles an architecture. Node resolves that
// bare `tauri` as a module path relative to the working directory — the failure
// without this file is `Cannot find module '<root>/src-tauri/tauri'` — so there
// has to be something *named* `tauri` reachable from here that actually runs the
// CLI.
//
// The installed CLI is `@tauri-apps/cli`, whose runnable entry point is
// `tauri.js` inside the package (`main.js` only exports an API and would do
// nothing if it were loaded instead). This project installs its dependencies
// with pnpm, which does not flatten packages into a top-level `node_modules/tauri`
// the way this template assumes, which is exactly the gap this shim fills: it
// resolves `@tauri-apps/cli` through the ordinary node_modules lookup that walks
// up out of `src-tauri/`, and loads the package's real entry point, which parses
// argv, runs the CLI, and exits non-zero on failure.
//
// It lives here rather than in `gen/android/` on purpose: everything under
// `gen/android/` is generated by `tauri android init` and would be overwritten,
// while this file is not part of any template.
//
// An `import` rather than a `require`, because the root `package.json` declares
// `"type": "module"` and so this file is an ES module; the target is CommonJS
// (`"type": "commonjs"` in that package), which Node happily loads and runs from
// an ES module.
import "@tauri-apps/cli/tauri.js";

